"""
Train Random Forest and XGBoost models to predict Soil Sustainability
Score (SSS) category from raw soil parameters.

Uses data/processed/akola_soil_scored.csv (output of
src/scoring/score_dataset.py) as the labeled dataset — the 'category'
column (Highly Sustainable / Moderately Sustainable / Needs Improvement /
Unsustainable) generated by the rule-based scoring engine becomes the
ML target.

Run with: python src/models/train_models.py

NOTE ON DATASET SIZE:
    86 samples is small for ML. Results here are a reasonable proof of
    concept for a college/demo project, but should not be over-interpreted
    as production-grade accuracy. A train/test split this small also means
    metrics can shift noticeably between runs — that's expected, not a bug.
"""

import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix
)
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb
import joblib

SCORED_DATA_PATH = Path("data/processed/akola_soil_scored.csv")
MODEL_OUTPUT_DIR = Path("src/models/saved")

# Features the models will learn from — raw soil parameters, NOT the
# already-computed chemical/physical sub-scores (that would be leaking
# the rule-based answer directly into the model).
FEATURE_COLUMNS = [
    "ph", "ec", "organic_carbon", "nitrogen",
    "phosphorus", "potassium", "texture_score",
]
TARGET_COLUMN = "category"


def load_data():
    df = pd.read_csv(SCORED_DATA_PATH)
    print(f"Loaded {len(df)} scored soil profiles")
    print(f"Category distribution:\n{df[TARGET_COLUMN].value_counts()}\n")
    return df


def prepare_features(df: pd.DataFrame):
    X = df[FEATURE_COLUMNS]
    y_raw = df[TARGET_COLUMN]

    encoder = LabelEncoder()
    y = encoder.fit_transform(y_raw)

    return X, y, encoder


def train_random_forest(X_train, y_train):
    model = RandomForestClassifier(
        n_estimators=200,
        max_depth=6,          # kept shallow — small dataset, avoid overfitting
        random_state=42,
        class_weight="balanced",
    )
    model.fit(X_train, y_train)
    return model


def train_xgboost(X_train, y_train, num_classes):
    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=4,           # shallow — small dataset, avoid overfitting
        learning_rate=0.1,
        objective="multi:softmax",
        num_class=num_classes,
        random_state=42,
        eval_metric="mlogloss",
    )
    model.fit(X_train, y_train)
    return model


def evaluate(name, model, X_test, y_test, encoder):
    preds = model.predict(X_test)
    acc = accuracy_score(y_test, preds)
    print(f"\n=== {name} ===")
    print(f"Accuracy: {acc:.2%}")
    print("\nClassification report:")
    print(classification_report(
        y_test, preds, target_names=encoder.classes_, zero_division=0
    ))
    print("Confusion matrix (rows=actual, cols=predicted):")
    print(pd.DataFrame(
        confusion_matrix(y_test, preds),
        index=encoder.classes_, columns=encoder.classes_
    ))
    return acc


def print_feature_importance(name, model, feature_names):
    importances = model.feature_importances_
    ranked = sorted(zip(feature_names, importances), key=lambda x: -x[1])
    print(f"\n{name} feature importance:")
    for feat, imp in ranked:
        print(f"  {feat:<20} {imp:.3f}")


def main():
    df = load_data()
    X, y, encoder = prepare_features(df)

    # Small dataset — stratify to keep class balance similar in train/test
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=42, stratify=y
    )
    print(f"Train size: {len(X_train)}, Test size: {len(X_test)}\n")

    rf_model = train_random_forest(X_train, y_train)
    rf_acc = evaluate("Random Forest", rf_model, X_test, y_test, encoder)
    print_feature_importance("Random Forest", rf_model, FEATURE_COLUMNS)

    xgb_model = train_xgboost(X_train, y_train, num_classes=len(encoder.classes_))
    xgb_acc = evaluate("XGBoost", xgb_model, X_test, y_test, encoder)
    print_feature_importance("XGBoost", xgb_model, FEATURE_COLUMNS)

    print("\n=== Summary ===")
    print(f"Random Forest accuracy: {rf_acc:.2%}")
    print(f"XGBoost accuracy:       {xgb_acc:.2%}")

    # Save both models + the label encoder for later use in the API
    MODEL_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(rf_model, MODEL_OUTPUT_DIR / "random_forest_model.pkl")
    joblib.dump(xgb_model, MODEL_OUTPUT_DIR / "xgboost_model.pkl")
    joblib.dump(encoder, MODEL_OUTPUT_DIR / "label_encoder.pkl")
    print(f"\nModels saved to {MODEL_OUTPUT_DIR}/")


if __name__ == "__main__":
    main()